DOMAINS:
  {
    "grafana": "grafana",
    "prometheus": "prome",
    "alertmanager": "alert",
    "k8sDashboard": "k8s",
    "ceph": "ceph",
    "httpreq": "httpreq",
  }
ENV_FILE_SOURCE: '/etc/profile'
K8S_HA_VIP: ''
K8S_API_DOMAIN: 'k8s-api'
K8S_API_PORT: '16443'
K8S_DEFAULE_NAMESPACE: 'default'
K8S_USER: 'ubuntu'
K8S_CIDRBLOCK: '10.244.0.0/16'
# K8S_CIDRBLOCK: '192.168.0.0/16'
INGRESS_NGINX_HTTP_PORT: 30478
INGRESS_NGINX_HTTPS_PORT: 30487
OS_USER: 'ubuntu'

# please don't do the evil w/ my demo account for newbie
DOCKER_REGISTRY: 'jasoncheng'
DOCKER_USER: 'jasoncheng'
DOCKER_PASS: 'dckr_pat_rfPcLh1ogXsajGfe8Es8trWUuis'